<?php

const ODDELOVAC_ADRESARU = '/';

const ADRESAR_KNIHOVNY = 'Knihovny';
const ADRESAR_GRAFIKA = 'Grafika';

const HLAVNI_TRIDA_SMARTY = 'Smarty-3.1.16/libs/Smarty.class.php';

const SOUBOR_STYLU = 'hlavni.css';
const SOUBOR_SKRIPTU = 'hlavni.js';

const ADRESA_JQUERY = '//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js';


/* Smarty */
const ADRESAR_SMARTY = 'Smarty';
const ADRESAR_SMARTY_SABLONY = 'Sablony';
const ADRESAR_SMARTY_KOMPILACNI = 'Kompilacni Adresar';
const ADRESAR_SMARTY_NASTAVENI = 'Nastaveni';
const ADRESAR_SMARTY_CACHE = 'Cache';

define('CESTA_KOREN_WEBU', getcwd());
define('ADRESA_KOREN_WEBU', "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]");

/********************
 *  CESTY
 *******************/
define('CESTA_ADRESAR_OBRAZKU', CESTA_KOREN_WEBU . ODDELOVAC_ADRESARU . ADRESAR_GRAFIKA);

/* Smatry */
define('CESTA_SMARTY_KNIHOVNA', CESTA_KOREN_WEBU . ODDELOVAC_ADRESARU . ADRESAR_KNIHOVNY . ODDELOVAC_ADRESARU .
    HLAVNI_TRIDA_SMARTY);

define('CESTA_SMARTY_SOUBORY', CESTA_KOREN_WEBU . ODDELOVAC_ADRESARU . ADRESAR_SMARTY);
define('CESTA_SMARTY_SABLONY', CESTA_SMARTY_SOUBORY . ODDELOVAC_ADRESARU . ADRESAR_SMARTY_SABLONY . ODDELOVAC_ADRESARU);
define('CESTA_SMARTY_KOMPILACNI_ADRESAR', CESTA_SMARTY_SOUBORY . ODDELOVAC_ADRESARU . ADRESAR_SMARTY_KOMPILACNI .
    ODDELOVAC_ADRESARU);
define('CESTA_SMARTY_NASTAVENI', CESTA_SMARTY_SOUBORY . ODDELOVAC_ADRESARU . ADRESAR_SMARTY_NASTAVENI .
    ODDELOVAC_ADRESARU);
define('CESTA_SMARTY_CACHE', CESTA_SMARTY_SOUBORY . ODDELOVAC_ADRESARU . ADRESAR_SMARTY_CACHE . ODDELOVAC_ADRESARU);


/********************
 *  ADRESY
 *******************/
define('ADRESA_GLOBALNI_STYL', ADRESA_KOREN_WEBU . ODDELOVAC_ADRESARU . SOUBOR_STYLU);
define('ADRESA_GLOBALNI_SKRIPT', ADRESA_KOREN_WEBU . ODDELOVAC_ADRESARU . SOUBOR_SKRIPTU);

define('ADRESA_ADRESAR_GRAFIKA', ADRESA_KOREN_WEBU . ODDELOVAC_ADRESARU . ADRESAR_GRAFIKA);


